/**
 * Book Library Catalog — 74 curated parenting & education books
 * Metadata for each book (title, author, category, descriptions)
 * Content is generated separately in book-library-content.ts
 */

export interface BookCatalogEntry {
  slug: string;
  title: string;
  author: string;
  category: BookCategory;
  subcategory: string;
  publication_year: number;
  cover_gradient: string;
  icon_emoji: string;
  short_description: string;
  why_we_picked: string;
  is_free_online: boolean;
  free_url?: string;
}

export type BookCategory =
  | 'core-parenting'
  | 'mindset-learning'
  | 'play-nature-body'
  | 'emotional-intelligence'
  | 'education-philosophy'
  | 'neurodiversity'
  | 'digital-age'
  | 'culture-community'
  | 'baby-early-years'
  | 'sleep-feeding'
  | 'teenagers'
  | 'discipline-frameworks'
  | 'gender-specific'
  | 'literacy-math';

export const BOOK_CATEGORIES: Record<BookCategory, { label: string; emoji: string; gradient: string }> = {
  'core-parenting': { label: 'Core Parenting & Child Development', emoji: '🧒', gradient: 'from-rose-500 to-pink-600' },
  'mindset-learning': { label: 'Mindset, Grit & Learning', emoji: '🧠', gradient: 'from-amber-500 to-orange-500' },
  'play-nature-body': { label: 'Play, Nature & Body', emoji: '🌿', gradient: 'from-emerald-500 to-green-600' },
  'emotional-intelligence': { label: 'Emotional Intelligence & Empathy', emoji: '💛', gradient: 'from-yellow-500 to-amber-500' },
  'education-philosophy': { label: 'Education Philosophy & Approaches', emoji: '🎓', gradient: 'from-purple-500 to-violet-600' },
  'neurodiversity': { label: 'Neurodiversity & Inclusion', emoji: '🌈', gradient: 'from-cyan-500 to-blue-500' },
  'digital-age': { label: 'Digital Age & Modern Challenges', emoji: '📱', gradient: 'from-slate-500 to-gray-700' },
  'culture-community': { label: 'Culture, Community & Global', emoji: '🌍', gradient: 'from-teal-500 to-emerald-600' },
  'baby-early-years': { label: 'Baby & Early Years', emoji: '👶', gradient: 'from-pink-400 to-rose-500' },
  'sleep-feeding': { label: 'Sleep & Feeding', emoji: '🍼', gradient: 'from-blue-400 to-indigo-500' },
  'teenagers': { label: 'Teenagers & Adolescence', emoji: '🧑‍🎓', gradient: 'from-indigo-500 to-purple-600' },
  'discipline-frameworks': { label: 'Discipline Frameworks', emoji: '⚖️', gradient: 'from-orange-500 to-red-500' },
  'gender-specific': { label: 'Gender-Specific Development', emoji: '♀️♂️', gradient: 'from-fuchsia-500 to-pink-600' },
  'literacy-math': { label: 'Literacy & Math', emoji: '📚', gradient: 'from-sky-500 to-blue-600' },
};

export const BOOK_CATALOG: BookCatalogEntry[] = [
  // ══════════════════════════════════════════════════════════════════════
  // CORE PARENTING & CHILD DEVELOPMENT (12)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'the-whole-brain-child',
    title: 'The Whole-Brain Child',
    author: 'Daniel J. Siegel & Tina Payne Bryson',
    category: 'core-parenting',
    subcategory: 'Brain Science',
    publication_year: 2011,
    cover_gradient: 'from-blue-600 to-indigo-700',
    icon_emoji: '🧠',
    short_description: '12 revolutionary strategies to nurture your child\'s developing mind by integrating brain science with everyday parenting.',
    why_we_picked: 'Translates complex neuroscience into simple, actionable strategies that any parent can use in daily moments — from tantrums to bedtime.',
    is_free_online: false,
  },
  {
    slug: 'parenting-from-the-inside-out',
    title: 'Parenting from the Inside Out',
    author: 'Daniel J. Siegel & Mary Hartzell',
    category: 'core-parenting',
    subcategory: 'Self-Awareness',
    publication_year: 2003,
    cover_gradient: 'from-violet-600 to-purple-700',
    icon_emoji: '🪞',
    short_description: 'How understanding your own childhood experiences can help you become a better parent.',
    why_we_picked: 'Most parenting books tell you what to do — this one helps you understand why you react the way you do, which is the real key to change.',
    is_free_online: false,
  },
  {
    slug: 'how-to-talk-so-kids-will-listen',
    title: 'How to Talk So Kids Will Listen & Listen So Kids Will Talk',
    author: 'Adele Faber & Elaine Mazlish',
    category: 'core-parenting',
    subcategory: 'Communication',
    publication_year: 1980,
    cover_gradient: 'from-green-600 to-emerald-700',
    icon_emoji: '🗣️',
    short_description: 'The classic guide to communicating with children in ways that build cooperation, self-esteem, and connection.',
    why_we_picked: 'Over 40 years old and still the gold standard. The practical dialogue examples make it immediately usable.',
    is_free_online: false,
  },
  {
    slug: 'the-self-driven-child',
    title: 'The Self-Driven Child',
    author: 'William Stixrud & Ned Johnson',
    category: 'core-parenting',
    subcategory: 'Autonomy',
    publication_year: 2018,
    cover_gradient: 'from-teal-600 to-cyan-700',
    icon_emoji: '🧭',
    short_description: 'The science and sense of giving kids more control over their own lives to reduce stress and build motivation.',
    why_we_picked: 'A powerful antidote to over-parenting. Backed by neuroscience showing that a sense of control is the key to motivation and mental health.',
    is_free_online: false,
  },
  {
    slug: 'raising-an-emotionally-intelligent-child',
    title: 'Raising an Emotionally Intelligent Child',
    author: 'John Gottman',
    category: 'core-parenting',
    subcategory: 'Emotional Development',
    publication_year: 1997,
    cover_gradient: 'from-red-500 to-rose-700',
    icon_emoji: '❤️',
    short_description: 'Research-based strategies for emotion coaching — helping children understand, express, and regulate their feelings.',
    why_we_picked: 'Gottman\'s research on emotional coaching is foundational. Kids whose parents use these techniques have better focus, friendships, and health.',
    is_free_online: false,
  },
  {
    slug: 'permission-to-feel',
    title: 'Permission to Feel',
    author: 'Marc Brackett',
    category: 'core-parenting',
    subcategory: 'Emotional Literacy',
    publication_year: 2019,
    cover_gradient: 'from-orange-500 to-amber-600',
    icon_emoji: '🎭',
    short_description: 'Unlocking the power of emotions to help children (and adults) thrive using the RULER approach.',
    why_we_picked: 'Introduces the RULER framework (Recognize, Understand, Label, Express, Regulate) — practical emotional literacy for the whole family.',
    is_free_online: false,
  },
  {
    slug: 'the-explosive-child',
    title: 'The Explosive Child',
    author: 'Ross W. Greene',
    category: 'core-parenting',
    subcategory: 'Challenging Behavior',
    publication_year: 1998,
    cover_gradient: 'from-red-600 to-orange-700',
    icon_emoji: '🌋',
    short_description: 'A compassionate, effective approach for understanding and helping children who are chronically inflexible and easily frustrated.',
    why_we_picked: 'Reframes "difficult" kids as kids with lagging skills rather than bad attitudes. The Collaborative & Proactive Solutions model works.',
    is_free_online: false,
  },
  {
    slug: 'raising-a-secure-child',
    title: 'Raising a Secure Child',
    author: 'Kent Hoffman, Glen Cooper & Bert Powell',
    category: 'core-parenting',
    subcategory: 'Attachment',
    publication_year: 2017,
    cover_gradient: 'from-sky-600 to-blue-700',
    icon_emoji: '🤗',
    short_description: 'How the Circle of Security approach helps parents create strong, healthy emotional bonds with their children.',
    why_we_picked: 'Attachment theory made practical. The Circle of Security visual is one of the clearest models for understanding what children need emotionally.',
    is_free_online: false,
  },
  {
    slug: 'elevating-child-care',
    title: 'Elevating Child Care: A Guide to Respectful Parenting',
    author: 'Janet Lansbury',
    category: 'core-parenting',
    subcategory: 'Respectful Parenting',
    publication_year: 2014,
    cover_gradient: 'from-amber-500 to-yellow-600',
    icon_emoji: '✨',
    short_description: 'RIE-inspired respectful parenting — treating even the youngest children as capable, whole people.',
    why_we_picked: 'Janet Lansbury made the RIE philosophy accessible to millions. Short, practical chapters that shift how you see your baby or toddler.',
    is_free_online: false,
  },
  {
    slug: 'no-drama-discipline',
    title: 'No-Drama Discipline',
    author: 'Daniel J. Siegel & Tina Payne Bryson',
    category: 'core-parenting',
    subcategory: 'Discipline',
    publication_year: 2014,
    cover_gradient: 'from-purple-500 to-fuchsia-600',
    icon_emoji: '🧩',
    short_description: 'The whole-brain way to calm the chaos and nurture your child\'s developing mind through discipline moments.',
    why_we_picked: 'Reframes discipline as a teaching opportunity, not punishment. The "connect then redirect" approach is backed by brain science.',
    is_free_online: false,
  },
  {
    slug: 'unconditional-parenting',
    title: 'Unconditional Parenting',
    author: 'Alfie Kohn',
    category: 'core-parenting',
    subcategory: 'Philosophy',
    publication_year: 2005,
    cover_gradient: 'from-indigo-600 to-violet-700',
    icon_emoji: '💜',
    short_description: 'Moving from rewards and punishments to love and reason — why children need unconditional support.',
    why_we_picked: 'Challenges assumptions about praise, rewards, and consequences that most parents never question. Thought-provoking and research-backed.',
    is_free_online: false,
  },
  {
    slug: 'the-montessori-toddler',
    title: 'The Montessori Toddler',
    author: 'Simone Davies',
    category: 'core-parenting',
    subcategory: 'Montessori',
    publication_year: 2019,
    cover_gradient: 'from-emerald-500 to-teal-600',
    icon_emoji: '🌱',
    short_description: 'A practical guide to raising curious, responsible children in the Montessori way at home.',
    why_we_picked: 'The most accessible Montessori book for parents — beautifully designed with concrete ideas for home environment, routines, and activities.',
    is_free_online: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // MINDSET, GRIT & LEARNING (8)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'mindset',
    title: 'Mindset: The New Psychology of Success',
    author: 'Carol S. Dweck',
    category: 'mindset-learning',
    subcategory: 'Growth Mindset',
    publication_year: 2006,
    cover_gradient: 'from-amber-600 to-orange-700',
    icon_emoji: '🌟',
    short_description: 'How a simple belief about intelligence — fixed vs. growth — shapes everything from learning to resilience.',
    why_we_picked: 'The foundational work on growth mindset. Understanding this one concept transforms how you praise, motivate, and talk to your children.',
    is_free_online: false,
  },
  {
    slug: 'grit',
    title: 'Grit: The Power of Passion and Perseverance',
    author: 'Angela Duckworth',
    category: 'mindset-learning',
    subcategory: 'Perseverance',
    publication_year: 2016,
    cover_gradient: 'from-red-600 to-rose-700',
    icon_emoji: '💪',
    short_description: 'Why talent alone doesn\'t guarantee success — and how passion combined with perseverance does.',
    why_we_picked: 'Duckworth\'s research shows grit predicts success more than IQ. Practical for parents thinking about how to nurture persistence.',
    is_free_online: false,
  },
  {
    slug: 'the-gift-of-failure',
    title: 'The Gift of Failure',
    author: 'Jessica Lahey',
    category: 'mindset-learning',
    subcategory: 'Resilience',
    publication_year: 2015,
    cover_gradient: 'from-slate-600 to-gray-700',
    icon_emoji: '🎁',
    short_description: 'How the best parents learn to let go so their children can succeed on their own terms.',
    why_we_picked: 'A necessary counterweight to helicopter parenting. Lahey shows that overprotecting actually undermines competence and confidence.',
    is_free_online: false,
  },
  {
    slug: 'range',
    title: 'Range: Why Generalists Triumph in a Specialized World',
    author: 'David Epstein',
    category: 'mindset-learning',
    subcategory: 'Breadth of Experience',
    publication_year: 2019,
    cover_gradient: 'from-cyan-600 to-teal-700',
    icon_emoji: '🎯',
    short_description: 'Why early specialization isn\'t always best — and how breadth of experience often leads to better outcomes.',
    why_we_picked: 'Essential reading for parents feeling pressure to specialize their kids early. The evidence for sampling widely is compelling.',
    is_free_online: false,
  },
  {
    slug: 'make-it-stick',
    title: 'Make It Stick: The Science of Successful Learning',
    author: 'Peter Brown, Henry Roediger & Mark McDaniel',
    category: 'mindset-learning',
    subcategory: 'Learning Science',
    publication_year: 2014,
    cover_gradient: 'from-yellow-600 to-amber-700',
    icon_emoji: '📌',
    short_description: 'Evidence-based techniques for effective learning — retrieval practice, spacing, interleaving, and more.',
    why_we_picked: 'Most study habits are wrong. This book distills cognitive science into concrete techniques that parents can teach their kids.',
    is_free_online: false,
  },
  {
    slug: 'einstein-never-used-flashcards',
    title: 'Einstein Never Used Flashcards',
    author: 'Kathy Hirsh-Pasek & Roberta Golinkoff',
    category: 'mindset-learning',
    subcategory: 'Play-Based Learning',
    publication_year: 2003,
    cover_gradient: 'from-blue-500 to-sky-600',
    icon_emoji: '🧪',
    short_description: 'How children really learn — and why more play and less screen time, testing, and scheduling is better.',
    why_we_picked: 'Two leading developmental psychologists dismantle the "earlier is better" myth with research showing play is the real engine of learning.',
    is_free_online: false,
  },
  {
    slug: 'free-to-learn',
    title: 'Free to Learn',
    author: 'Peter Gray',
    category: 'mindset-learning',
    subcategory: 'Self-Directed Learning',
    publication_year: 2013,
    cover_gradient: 'from-green-600 to-emerald-700',
    icon_emoji: '🦋',
    short_description: 'Why unleashing the instinct to play will make children happier, more self-reliant, and better students.',
    why_we_picked: 'A compelling evolutionary psychology argument for why children need more freedom and play, with evidence from hunter-gatherer societies to Sudbury schools.',
    is_free_online: false,
  },
  {
    slug: 'how-children-learn',
    title: 'How Children Learn',
    author: 'John Holt',
    category: 'mindset-learning',
    subcategory: 'Natural Learning',
    publication_year: 1967,
    cover_gradient: 'from-stone-600 to-amber-800',
    icon_emoji: '👀',
    short_description: 'A classic observation-based look at how children naturally learn through games, experiments, talk, reading, and sports.',
    why_we_picked: 'Holt\'s patient observations of children learning are timeless. He shows that children are natural learners — when adults get out of the way.',
    is_free_online: true,
    free_url: 'http://schoolofeducators.com/wp-content/uploads/2011/12/HOW-CHILDREN-LEARN-JOHN-HOLT.pdf',
  },

  // ══════════════════════════════════════════════════════════════════════
  // PLAY, NATURE & BODY (6)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'last-child-in-the-woods',
    title: 'Last Child in the Woods',
    author: 'Richard Louv',
    category: 'play-nature-body',
    subcategory: 'Nature Deficit',
    publication_year: 2005,
    cover_gradient: 'from-green-700 to-emerald-800',
    icon_emoji: '🌲',
    short_description: 'Saving our children from nature-deficit disorder — why kids need the outdoors more than ever.',
    why_we_picked: 'Coined "nature-deficit disorder" and sparked a global movement. The research linking nature exposure to attention, creativity, and well-being is powerful.',
    is_free_online: false,
  },
  {
    slug: 'balanced-and-barefoot',
    title: 'Balanced and Barefoot',
    author: 'Angela Hanscom',
    category: 'play-nature-body',
    subcategory: 'Sensory-Motor',
    publication_year: 2016,
    cover_gradient: 'from-lime-600 to-green-700',
    icon_emoji: '🦶',
    short_description: 'How unrestricted outdoor play makes for strong, confident, and capable children.',
    why_we_picked: 'Written by an occupational therapist, this shows why modern indoor childhoods are creating sensory and motor deficits — and what to do about it.',
    is_free_online: false,
  },
  {
    slug: 'the-art-of-roughhousing',
    title: 'The Art of Roughhousing',
    author: 'Anthony DeBenedet & Lawrence Cohen',
    category: 'play-nature-body',
    subcategory: 'Physical Play',
    publication_year: 2011,
    cover_gradient: 'from-orange-600 to-red-600',
    icon_emoji: '🤸',
    short_description: 'A celebration of active, physical play and why it makes kids smarter, more resilient, and more emotionally intelligent.',
    why_we_picked: 'Counters the "be careful" culture with research showing roughhousing builds emotional regulation, social skills, and physical confidence.',
    is_free_online: false,
  },
  {
    slug: 'theres-no-such-thing-as-bad-weather',
    title: 'There\'s No Such Thing as Bad Weather',
    author: 'Linda Åkeson McGurk',
    category: 'play-nature-body',
    subcategory: 'Scandinavian Outdoors',
    publication_year: 2017,
    cover_gradient: 'from-sky-600 to-blue-700',
    icon_emoji: '🌧️',
    short_description: 'A Scandinavian mom\'s guide to raising kids who embrace the outdoors in all seasons.',
    why_we_picked: 'Bridges Scandinavian outdoor culture with American parenting. Practical, warm, and inspiring for getting kids outside year-round.',
    is_free_online: false,
  },
  {
    slug: 'spark',
    title: 'Spark: The Revolutionary New Science of Exercise and the Brain',
    author: 'John J. Ratey',
    category: 'play-nature-body',
    subcategory: 'Exercise & Brain',
    publication_year: 2008,
    cover_gradient: 'from-yellow-500 to-orange-600',
    icon_emoji: '⚡',
    short_description: 'How exercise transforms the brain — improving learning, mood, attention, and mental health.',
    why_we_picked: 'The definitive book on how physical movement directly impacts brain development, learning, and emotional regulation in children.',
    is_free_online: false,
  },
  {
    slug: 'playful-learning',
    title: 'Playful Learning',
    author: 'Mariah Bruehl',
    category: 'play-nature-body',
    subcategory: 'Learning Through Play',
    publication_year: 2011,
    cover_gradient: 'from-pink-500 to-rose-600',
    icon_emoji: '🎨',
    short_description: 'Practical activities that prove play is the most powerful vehicle for learning in the early years.',
    why_we_picked: 'Beautiful, hands-on activity ideas grounded in research. Perfect for parents who want to make learning joyful and play-based at home.',
    is_free_online: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // EMOTIONAL INTELLIGENCE & EMPATHY (5)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'unselfie',
    title: 'Unselfie: Why Empathetic Kids Succeed in Our All-About-Me World',
    author: 'Michele Borba',
    category: 'emotional-intelligence',
    subcategory: 'Empathy',
    publication_year: 2016,
    cover_gradient: 'from-pink-600 to-fuchsia-700',
    icon_emoji: '🫂',
    short_description: 'Nine habits to develop empathy in children in an age of increasing narcissism and self-focus.',
    why_we_picked: 'Borba presents a clear, research-backed roadmap for building empathy — the trait most linked to happiness, resilience, and success.',
    is_free_online: false,
  },
  {
    slug: 'sitting-still-like-a-frog',
    title: 'Sitting Still Like a Frog',
    author: 'Eline Snel',
    category: 'emotional-intelligence',
    subcategory: 'Mindfulness',
    publication_year: 2013,
    cover_gradient: 'from-green-500 to-teal-600',
    icon_emoji: '🐸',
    short_description: 'Simple mindfulness exercises for kids ages 5-12 to manage emotions, improve concentration, and handle anxiety.',
    why_we_picked: 'The most accessible children\'s mindfulness book. Short, fun exercises that kids actually enjoy doing. Includes audio meditations.',
    is_free_online: false,
  },
  {
    slug: 'planting-seeds',
    title: 'Planting Seeds: Practicing Mindfulness with Children',
    author: 'Thich Nhat Hanh',
    category: 'emotional-intelligence',
    subcategory: 'Mindfulness',
    publication_year: 2011,
    cover_gradient: 'from-emerald-600 to-green-700',
    icon_emoji: '🌻',
    short_description: 'Gentle mindfulness practices for children and families from the beloved Zen master.',
    why_we_picked: 'Thich Nhat Hanh brings a depth and simplicity that other mindfulness books lack. Beautiful activities for cultivating peace in family life.',
    is_free_online: false,
  },
  {
    slug: 'the-body-keeps-the-score',
    title: 'The Body Keeps the Score',
    author: 'Bessel van der Kolk',
    category: 'emotional-intelligence',
    subcategory: 'Trauma & Healing',
    publication_year: 2014,
    cover_gradient: 'from-slate-700 to-gray-800',
    icon_emoji: '🏛️',
    short_description: 'How trauma reshapes the body and brain — and innovative approaches to recovery and healing.',
    why_we_picked: 'Essential for any parent dealing with their own or their child\'s trauma. Understanding the body-brain connection changes everything about healing.',
    is_free_online: false,
  },
  {
    slug: 'raising-good-humans',
    title: 'Raising Good Humans',
    author: 'Hunter Clarke-Fields',
    category: 'emotional-intelligence',
    subcategory: 'Mindful Parenting',
    publication_year: 2019,
    cover_gradient: 'from-amber-500 to-yellow-600',
    icon_emoji: '🌞',
    short_description: 'A mindful guide to breaking the cycle of reactive parenting and raising kind, confident kids.',
    why_we_picked: 'Combines mindfulness with practical parenting. Focuses on the parent\'s self-regulation first — because you can\'t pour from an empty cup.',
    is_free_online: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // EDUCATION PHILOSOPHY & APPROACHES (7)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'montessori-science-behind-the-genius',
    title: 'Montessori: The Science Behind the Genius',
    author: 'Angeline Stoll Lillard',
    category: 'education-philosophy',
    subcategory: 'Montessori Research',
    publication_year: 2005,
    cover_gradient: 'from-violet-600 to-indigo-700',
    icon_emoji: '🔬',
    short_description: 'The definitive research-based case for Montessori education — connecting each principle to peer-reviewed science.',
    why_we_picked: 'The most rigorous academic validation of Montessori methods. Essential for parents who want evidence, not just philosophy.',
    is_free_online: false,
  },
  {
    slug: 'finnish-lessons',
    title: 'Finnish Lessons 3.0',
    author: 'Pasi Sahlberg',
    category: 'education-philosophy',
    subcategory: 'Education Systems',
    publication_year: 2021,
    cover_gradient: 'from-blue-600 to-sky-700',
    icon_emoji: '🇫🇮',
    short_description: 'What the world can learn from the Finnish education system — less testing, more trust, better outcomes.',
    why_we_picked: 'Finland consistently outperforms while doing the opposite of most countries. Sahlberg explains why trust, equity, and play work better than pressure.',
    is_free_online: false,
  },
  {
    slug: 'the-element',
    title: 'The Element: How Finding Your Passion Changes Everything',
    author: 'Ken Robinson',
    category: 'education-philosophy',
    subcategory: 'Creativity & Passion',
    publication_year: 2009,
    cover_gradient: 'from-orange-500 to-rose-600',
    icon_emoji: '🔥',
    short_description: 'How finding the intersection of natural talent and personal passion leads to fulfillment and achievement.',
    why_we_picked: 'Ken Robinson\'s vision for education that nurtures creativity and individuality. His TED talk has 75M views for a reason.',
    is_free_online: false,
  },
  {
    slug: 'lifelong-kindergarten',
    title: 'Lifelong Kindergarten',
    author: 'Mitchel Resnick',
    category: 'education-philosophy',
    subcategory: 'Creative Learning',
    publication_year: 2017,
    cover_gradient: 'from-yellow-500 to-orange-500',
    icon_emoji: '🧱',
    short_description: 'Why the creative, playful learning approach of kindergarten should extend through all of education.',
    why_we_picked: 'From the creator of Scratch. Makes a compelling case that the project-based, creative approach of kindergarten is how everyone learns best.',
    is_free_online: false,
  },
  {
    slug: 'summerhill',
    title: 'Summerhill: A Radical Approach to Child Rearing',
    author: 'A.S. Neill',
    category: 'education-philosophy',
    subcategory: 'Democratic Education',
    publication_year: 1960,
    cover_gradient: 'from-stone-600 to-amber-700',
    icon_emoji: '🏫',
    short_description: 'The legendary free school where children govern themselves, attendance is optional, and happiness comes first.',
    why_we_picked: 'The original radical experiment in child freedom. Whether or not you agree with everything, it challenges fundamental assumptions about education.',
    is_free_online: true,
    free_url: 'https://archive.org/stream/Summerhill-English-A.S.Neill/summerhill_djvu.txt',
  },
  {
    slug: 'the-brave-learner',
    title: 'The Brave Learner',
    author: 'Julie Bogart',
    category: 'education-philosophy',
    subcategory: 'Homeschooling',
    publication_year: 2019,
    cover_gradient: 'from-rose-500 to-pink-600',
    icon_emoji: '🦁',
    short_description: 'Finding everyday magic in homeschool, learning, and life — making education an adventure.',
    why_we_picked: 'Whether homeschooling or not, Bogart\'s philosophy of curiosity-led, joyful learning transforms how parents think about education at home.',
    is_free_online: false,
  },
  {
    slug: 'creative-confidence',
    title: 'Creative Confidence',
    author: 'Tom Kelley & David Kelley',
    category: 'education-philosophy',
    subcategory: 'Creativity',
    publication_year: 2013,
    cover_gradient: 'from-fuchsia-500 to-purple-600',
    icon_emoji: '💡',
    short_description: 'Unleashing the creative potential that exists in everyone — from the founders of IDEO and Stanford d.school.',
    why_we_picked: 'Shows that creativity isn\'t a gift for the few — it\'s a skill anyone can develop. The design thinking approach applies beautifully to parenting.',
    is_free_online: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // NEURODIVERSITY & INCLUSION (4)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'uniquely-human',
    title: 'Uniquely Human: A Different Way of Seeing Autism',
    author: 'Barry Prizant',
    category: 'neurodiversity',
    subcategory: 'Autism',
    publication_year: 2015,
    cover_gradient: 'from-cyan-600 to-blue-700',
    icon_emoji: '🧩',
    short_description: 'A compassionate reframing of autism — seeing behaviors as adaptive strategies rather than problems to fix.',
    why_we_picked: 'Transforms how you think about autism. Instead of "fixing" behaviors, Prizant shows how to understand and support the person behind them.',
    is_free_online: false,
  },
  {
    slug: 'differently-wired',
    title: 'Differently Wired',
    author: 'Debbie Reber',
    category: 'neurodiversity',
    subcategory: 'Neurodivergent Children',
    publication_year: 2018,
    cover_gradient: 'from-violet-500 to-fuchsia-600',
    icon_emoji: '⚡',
    short_description: 'Raising an exceptional child in a conventional world — 18 paradigm shifts for parenting differently wired kids.',
    why_we_picked: 'Practical and empowering for parents of kids with ADHD, autism, giftedness, learning differences, or any combination. You\'re not alone.',
    is_free_online: false,
  },
  {
    slug: 'the-way-they-learn',
    title: 'The Way They Learn',
    author: 'Cynthia Tobias',
    category: 'neurodiversity',
    subcategory: 'Learning Styles',
    publication_year: 1994,
    cover_gradient: 'from-indigo-500 to-blue-600',
    icon_emoji: '🔍',
    short_description: 'Understanding different learning styles to help every child succeed — visual, auditory, kinesthetic, and beyond.',
    why_we_picked: 'Helps parents see that their child isn\'t struggling — they\'re just learning differently. Practical for adapting your approach to each child.',
    is_free_online: false,
  },
  {
    slug: 'smart-moves',
    title: 'Smart Moves: Why Learning Is Not All in Your Head',
    author: 'Carla Hannaford',
    category: 'neurodiversity',
    subcategory: 'Body-Brain Connection',
    publication_year: 1995,
    cover_gradient: 'from-teal-500 to-cyan-600',
    icon_emoji: '🤸‍♂️',
    short_description: 'How movement and the body are essential to learning — challenging the head-only model of education.',
    why_we_picked: 'Neuroscience showing that the body is a learning organ. Essential for understanding fidgety, active learners who need to move to think.',
    is_free_online: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // DIGITAL AGE & MODERN CHALLENGES (4)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'screenwise',
    title: 'Screenwise',
    author: 'Devorah Heitner',
    category: 'digital-age',
    subcategory: 'Digital Literacy',
    publication_year: 2016,
    cover_gradient: 'from-slate-600 to-gray-700',
    icon_emoji: '📱',
    short_description: 'Helping kids thrive and survive in their digital world — mentoring over monitoring.',
    why_we_picked: 'Takes a mentoring approach rather than fear-based restriction. Practical strategies for raising digital citizens, not just limiting screen time.',
    is_free_online: false,
  },
  {
    slug: 'the-tech-wise-family',
    title: 'The Tech-Wise Family',
    author: 'Andy Crouch',
    category: 'digital-age',
    subcategory: 'Technology Boundaries',
    publication_year: 2017,
    cover_gradient: 'from-blue-700 to-indigo-800',
    icon_emoji: '🏠',
    short_description: 'Everyday steps for putting technology in its proper place and building a family that values presence.',
    why_we_picked: 'Not anti-technology, but pro-intentional. Offers 10 concrete commitments for creating a healthier relationship with devices as a family.',
    is_free_online: false,
  },
  {
    slug: 'the-anxious-generation',
    title: 'The Anxious Generation',
    author: 'Jonathan Haidt',
    category: 'digital-age',
    subcategory: 'Mental Health & Phones',
    publication_year: 2024,
    cover_gradient: 'from-red-700 to-rose-800',
    icon_emoji: '📵',
    short_description: 'How the great rewiring of childhood through smartphones and social media is causing an epidemic of mental illness.',
    why_we_picked: 'The most important recent book on childhood and technology. Haidt presents alarming data and actionable solutions for parents and schools.',
    is_free_online: false,
  },
  {
    slug: 'media-moms-digital-dads',
    title: 'Media Moms & Digital Dads',
    author: 'Yalda Uhls',
    category: 'digital-age',
    subcategory: 'Media Research',
    publication_year: 2015,
    cover_gradient: 'from-purple-600 to-indigo-700',
    icon_emoji: '👨‍👩‍👧',
    short_description: 'A fact-based guide to navigating the science behind kids and screens, separating hype from reality.',
    why_we_picked: 'Cuts through the panic with actual research. A balanced, science-first approach to understanding how media affects children.',
    is_free_online: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // CULTURE, COMMUNITY & GLOBAL (4)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'braiding-sweetgrass',
    title: 'Braiding Sweetgrass',
    author: 'Robin Wall Kimmerer',
    category: 'culture-community',
    subcategory: 'Indigenous Wisdom',
    publication_year: 2013,
    cover_gradient: 'from-amber-700 to-green-800',
    icon_emoji: '🌾',
    short_description: 'Indigenous wisdom, scientific knowledge, and the teachings of plants — a beautiful integration of ways of knowing.',
    why_we_picked: 'Transforms how you think about our relationship with the natural world. Teaches gratitude, reciprocity, and connection that enriches parenting.',
    is_free_online: false,
  },
  {
    slug: 'growing-up-global',
    title: 'Growing Up Global',
    author: 'Homa Sabet Tavangar',
    category: 'culture-community',
    subcategory: 'Global Citizenship',
    publication_year: 2009,
    cover_gradient: 'from-teal-600 to-emerald-700',
    icon_emoji: '🌏',
    short_description: 'Raising children to be at home in the world — practical activities for developing global awareness.',
    why_we_picked: 'Packed with activities for raising globally-aware kids. Covers everything from world cuisines to pen pals to understanding different cultures.',
    is_free_online: false,
  },
  {
    slug: 'it-takes-a-village',
    title: 'It Takes a Village',
    author: 'Hillary Rodham Clinton',
    category: 'culture-community',
    subcategory: 'Community',
    publication_year: 1996,
    cover_gradient: 'from-blue-600 to-navy-700',
    icon_emoji: '🏘️',
    short_description: 'How the whole community — schools, businesses, churches, government — shares responsibility for raising children.',
    why_we_picked: 'A reminder that parenting was never meant to be done alone. The community-based approach to child-rearing resonates across cultures.',
    is_free_online: false,
  },
  {
    slug: 'hunt-gather-parent',
    title: 'Hunt, Gather, Parent',
    author: 'Michaeleen Doucleff',
    category: 'culture-community',
    subcategory: 'Cross-Cultural Parenting',
    publication_year: 2021,
    cover_gradient: 'from-orange-700 to-amber-800',
    icon_emoji: '🏕️',
    short_description: 'Ancient parenting wisdom from Maya, Inuit, and Hadzabe cultures that transforms modern family life.',
    why_we_picked: 'Doucleff lived with indigenous families and discovered parenting practices that solve problems Western culture struggles with — cooperation, calm, and helpfulness.',
    is_free_online: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // BABY & EARLY YEARS (4)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'what-to-expect-when-youre-expecting',
    title: 'What to Expect When You\'re Expecting',
    author: 'Heidi Murkoff',
    category: 'baby-early-years',
    subcategory: 'Pregnancy',
    publication_year: 1984,
    cover_gradient: 'from-pink-400 to-rose-500',
    icon_emoji: '🤰',
    short_description: 'The definitive pregnancy guide — week-by-week development, symptoms, nutrition, and preparation for birth.',
    why_we_picked: 'Named one of the most influential books of the last 25 years. The comprehensive pregnancy reference that generations of parents trust.',
    is_free_online: false,
  },
  {
    slug: 'the-happiest-baby-on-the-block',
    title: 'The Happiest Baby on the Block',
    author: 'Harvey Karp',
    category: 'baby-early-years',
    subcategory: 'Newborn Care',
    publication_year: 2002,
    cover_gradient: 'from-sky-400 to-blue-500',
    icon_emoji: '👶',
    short_description: 'The "5 S\'s" technique for calming fussy newborns — swaddling, side position, shushing, swinging, and sucking.',
    why_we_picked: 'The 5 S\'s have helped millions of exhausted new parents. Simple, effective, and based on understanding the "fourth trimester."',
    is_free_online: false,
  },
  {
    slug: 'expecting-better',
    title: 'Expecting Better',
    author: 'Emily Oster',
    category: 'baby-early-years',
    subcategory: 'Data-Driven Pregnancy',
    publication_year: 2013,
    cover_gradient: 'from-emerald-400 to-teal-500',
    icon_emoji: '📊',
    short_description: 'An economist evaluates the data behind pregnancy rules — challenging myths with actual evidence.',
    why_we_picked: 'Finally, someone looked at the actual data behind pregnancy advice. Empowers parents to make informed decisions rather than follow fear.',
    is_free_online: false,
  },
  {
    slug: 'cribsheet',
    title: 'Cribsheet',
    author: 'Emily Oster',
    category: 'baby-early-years',
    subcategory: 'Data-Driven Early Years',
    publication_year: 2019,
    cover_gradient: 'from-violet-400 to-purple-500',
    icon_emoji: '📈',
    short_description: 'A data-driven guide to better, more relaxed parenting from birth to preschool — sleep, feeding, health, and more.',
    why_we_picked: 'The companion to Expecting Better. Oster tackles the biggest first-year debates (breastfeeding, sleep training, daycare) with data, not judgment.',
    is_free_online: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // SLEEP & FEEDING (2)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'healthy-sleep-habits-happy-child',
    title: 'Healthy Sleep Habits, Happy Child',
    author: 'Marc Weissbluth',
    category: 'sleep-feeding',
    subcategory: 'Sleep',
    publication_year: 1987,
    cover_gradient: 'from-indigo-500 to-blue-600',
    icon_emoji: '😴',
    short_description: 'The comprehensive guide to understanding and solving children\'s sleep problems from birth through adolescence.',
    why_we_picked: 'Decades of pediatric sleep research distilled into practical guidance. Covers every age and every sleep challenge parents face.',
    is_free_online: false,
  },
  {
    slug: 'child-of-mine',
    title: 'Child of Mine: Feeding with Love and Good Sense',
    author: 'Ellyn Satter',
    category: 'sleep-feeding',
    subcategory: 'Feeding',
    publication_year: 2000,
    cover_gradient: 'from-green-500 to-emerald-600',
    icon_emoji: '🥗',
    short_description: 'The division of responsibility in feeding — parents decide what, when, and where; children decide how much and whether.',
    why_we_picked: 'The gold standard for feeding. Satter\'s division of responsibility framework prevents food battles and builds healthy eating for life.',
    is_free_online: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // TEENAGERS & ADOLESCENCE (4)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'untangled',
    title: 'Untangled',
    author: 'Lisa Damour',
    category: 'teenagers',
    subcategory: 'Teen Girls',
    publication_year: 2016,
    cover_gradient: 'from-purple-600 to-pink-700',
    icon_emoji: '🧶',
    short_description: 'Guiding teenage girls through the seven developmental transitions of adolescence.',
    why_we_picked: 'The essential guide to understanding what teenage girls are going through. Damour normalizes teen behavior while offering practical guidance.',
    is_free_online: false,
  },
  {
    slug: 'the-emotional-lives-of-teenagers',
    title: 'The Emotional Lives of Teenagers',
    author: 'Lisa Damour',
    category: 'teenagers',
    subcategory: 'Teen Emotions',
    publication_year: 2023,
    cover_gradient: 'from-indigo-600 to-violet-700',
    icon_emoji: '🎢',
    short_description: 'Raising connected, capable, and compassionate adolescents — understanding their intense emotional world.',
    why_we_picked: 'The most important recent book on teen mental health. Damour reframes strong emotions as healthy and shows parents how to be a steady presence.',
    is_free_online: false,
  },
  {
    slug: 'brainstorm',
    title: 'Brainstorm: The Power and Purpose of the Teenage Brain',
    author: 'Daniel J. Siegel',
    category: 'teenagers',
    subcategory: 'Teen Brain Science',
    publication_year: 2013,
    cover_gradient: 'from-cyan-600 to-blue-700',
    icon_emoji: '🧠',
    short_description: 'The teen brain explained — why adolescence is a vital period of emotional intensity, social engagement, and creativity.',
    why_we_picked: 'Siegel reframes adolescence as a time of tremendous potential rather than a problem phase. Understanding the teen brain changes everything.',
    is_free_online: false,
  },
  {
    slug: 'how-to-talk-so-teens-will-listen',
    title: 'How to Talk So Teens Will Listen and Listen So Teens Will Talk',
    author: 'Adele Faber & Elaine Mazlish',
    category: 'teenagers',
    subcategory: 'Teen Communication',
    publication_year: 2005,
    cover_gradient: 'from-green-600 to-teal-700',
    icon_emoji: '💬',
    short_description: 'The teen-specific companion to the classic — adapting respectful communication for the adolescent years.',
    why_we_picked: 'Extends the proven Faber & Mazlish approach to the unique challenges of teen communication — privacy, independence, and risk-taking.',
    is_free_online: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // DISCIPLINE FRAMEWORKS (4)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'good-inside',
    title: 'Good Inside',
    author: 'Becky Kennedy',
    category: 'discipline-frameworks',
    subcategory: 'Connection-Based Discipline',
    publication_year: 2022,
    cover_gradient: 'from-amber-500 to-orange-600',
    icon_emoji: '🌟',
    short_description: 'A guide to becoming the parent you want to be — sturdy leadership, firm boundaries, and deep connection.',
    why_we_picked: 'The #1 modern parenting voice. "Dr. Becky" reframes discipline around the principle that kids are fundamentally good inside.',
    is_free_online: false,
  },
  {
    slug: 'peaceful-parent-happy-kids',
    title: 'Peaceful Parent, Happy Kids',
    author: 'Laura Markham',
    category: 'discipline-frameworks',
    subcategory: 'Gentle Parenting',
    publication_year: 2012,
    cover_gradient: 'from-sky-500 to-cyan-600',
    icon_emoji: '☮️',
    short_description: 'How to stop yelling and start connecting — the practical guide to peaceful, respectful discipline.',
    why_we_picked: 'Bridges the gap between knowing you shouldn\'t yell and actually being able to stop. Markham\'s 3-step approach (regulate, connect, coach) works.',
    is_free_online: false,
  },
  {
    slug: 'positive-discipline',
    title: 'Positive Discipline',
    author: 'Jane Nelsen',
    category: 'discipline-frameworks',
    subcategory: 'Positive Discipline',
    publication_year: 1981,
    cover_gradient: 'from-blue-500 to-indigo-600',
    icon_emoji: '⭐',
    short_description: 'The classic guide to firm yet kind discipline — mutual respect, encouragement, and long-term character building.',
    why_we_picked: 'The 25+ year gold standard for respectful discipline. Nelsen\'s framework is used in homes and schools worldwide.',
    is_free_online: false,
  },
  {
    slug: 'no-bad-kids',
    title: 'No Bad Kids: Toddler Discipline Without Shame',
    author: 'Janet Lansbury',
    category: 'discipline-frameworks',
    subcategory: 'Toddler Discipline',
    publication_year: 2014,
    cover_gradient: 'from-rose-500 to-red-600',
    icon_emoji: '👧',
    short_description: 'Setting limits with respect and empathy — the RIE approach to toddler discipline without punishment or shame.',
    why_we_picked: 'Lansbury\'s most popular book. Short, practical chapters on handling hitting, biting, tantrums, and limit-testing with calm confidence.',
    is_free_online: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // GENDER-SPECIFIC DEVELOPMENT (2)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'reviving-ophelia',
    title: 'Reviving Ophelia',
    author: 'Mary Pipher',
    category: 'gender-specific',
    subcategory: 'Adolescent Girls',
    publication_year: 1994,
    cover_gradient: 'from-fuchsia-600 to-pink-700',
    icon_emoji: '🌸',
    short_description: 'The landmark book on saving the selves of adolescent girls in a media-saturated, image-obsessed culture.',
    why_we_picked: 'Shaped an entire generation of parenting. Pipher\'s insights on how culture pressures girls remain devastatingly relevant.',
    is_free_online: false,
  },
  {
    slug: 'raising-cain',
    title: 'Raising Cain: Protecting the Emotional Life of the Boy',
    author: 'Dan Kindlon & Michael Thompson',
    category: 'gender-specific',
    subcategory: 'Boys\' Emotions',
    publication_year: 1999,
    cover_gradient: 'from-blue-700 to-slate-800',
    icon_emoji: '🛡️',
    short_description: 'Understanding the emotional world of boys — why they struggle, what they need, and how to help them thrive.',
    why_we_picked: 'Boys are taught to suppress emotions from an early age. This book shows the devastating cost and offers a path to emotionally healthy masculinity.',
    is_free_online: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // NEURODIVERSITY ADDITIONS (2)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'taking-charge-of-adhd',
    title: 'Taking Charge of ADHD',
    author: 'Russell Barkley',
    category: 'neurodiversity',
    subcategory: 'ADHD',
    publication_year: 2013,
    cover_gradient: 'from-orange-600 to-red-700',
    icon_emoji: '🎯',
    short_description: 'The definitive guide to understanding and managing ADHD — from the world\'s leading researcher.',
    why_we_picked: 'The most comprehensive, research-backed ADHD parenting guide. Barkley\'s practical strategies address school, home, behavior, and medication.',
    is_free_online: false,
  },
  {
    slug: 'brain-body-parenting',
    title: 'Brain-Body Parenting',
    author: 'Mona Delahooke',
    category: 'neurodiversity',
    subcategory: 'Nervous System',
    publication_year: 2022,
    cover_gradient: 'from-teal-600 to-cyan-700',
    icon_emoji: '🫀',
    short_description: 'Understanding children\'s behavior through the nervous system lens — moving beyond behavioral approaches.',
    why_we_picked: 'A paradigm shift. Delahooke shows that behavior is communication from the body, not a discipline problem. Changes how you see every meltdown.',
    is_free_online: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // CROSS-CULTURAL & COMMUNICATION ADDITIONS (2)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'bringing-up-bebe',
    title: 'Bringing Up Bébé',
    author: 'Pamela Druckerman',
    category: 'culture-community',
    subcategory: 'French Parenting',
    publication_year: 2012,
    cover_gradient: 'from-rose-400 to-pink-500',
    icon_emoji: '🥐',
    short_description: 'An American mom discovers the secrets of French parenting — patience, autonomy, and the art of the "cadre."',
    why_we_picked: 'A fun, insightful look at how French families raise self-sufficient, well-behaved children without helicopter parenting or constant anxiety.',
    is_free_online: false,
  },
  {
    slug: 'how-to-talk-so-little-kids-will-listen',
    title: 'How to Talk So Little Kids Will Listen',
    author: 'Joanna Faber & Julie King',
    category: 'discipline-frameworks',
    subcategory: 'Ages 2-7 Communication',
    publication_year: 2017,
    cover_gradient: 'from-lime-500 to-green-600',
    icon_emoji: '🗨️',
    short_description: 'The updated Faber approach adapted specifically for ages 2-7 — practical tools for daily parenting battles.',
    why_we_picked: 'Takes the proven "How to Talk" method and adapts it for the unique chaos of toddlers and young children. Full of real-life examples.',
    is_free_online: false,
  },

  // ══════════════════════════════════════════════════════════════════════
  // NOTABLE ADDITIONS — LITERACY, MATH & BILINGUAL (4)
  // ══════════════════════════════════════════════════════════════════════
  {
    slug: 'simplicity-parenting',
    title: 'Simplicity Parenting',
    author: 'Kim John Payne',
    category: 'core-parenting',
    subcategory: 'Simplification',
    publication_year: 2009,
    cover_gradient: 'from-stone-500 to-amber-600',
    icon_emoji: '🍃',
    short_description: 'Using the power of less to raise calmer, happier, and more secure children in a busy world.',
    why_we_picked: 'A counter-cultural message that resonates deeply: fewer toys, less scheduling, more rhythm. Payne shows that simplification reduces anxiety and behavior issues.',
    is_free_online: false,
  },
  {
    slug: 'the-read-aloud-handbook',
    title: 'The Read-Aloud Handbook',
    author: 'Jim Trelease',
    category: 'literacy-math',
    subcategory: 'Reading',
    publication_year: 1982,
    cover_gradient: 'from-amber-600 to-orange-700',
    icon_emoji: '📖',
    short_description: 'The classic case for reading aloud — why it\'s the single most important thing you can do for your child\'s education.',
    why_we_picked: 'Decades of research showing reading aloud is the #1 predictor of school success. Includes a treasury of great read-aloud books by age.',
    is_free_online: false,
  },
  {
    slug: 'mathematical-mindsets',
    title: 'Mathematical Mindsets',
    author: 'Jo Boaler',
    category: 'literacy-math',
    subcategory: 'Math',
    publication_year: 2015,
    cover_gradient: 'from-blue-600 to-indigo-700',
    icon_emoji: '🔢',
    short_description: 'Unleashing students\' potential through creative math, inspiring messages, and innovative teaching — everyone can be a math person.',
    why_we_picked: 'Destroys the "I\'m not a math person" myth. Boaler shows how visual, creative, and growth-mindset approaches make math accessible and enjoyable.',
    is_free_online: false,
  },
  {
    slug: 'raising-a-bilingual-child',
    title: 'Raising a Bilingual Child',
    author: 'Barbara Zurer Pearson',
    category: 'literacy-math',
    subcategory: 'Bilingualism',
    publication_year: 2008,
    cover_gradient: 'from-teal-500 to-emerald-600',
    icon_emoji: '🌐',
    short_description: 'A comprehensive guide to raising bilingual children — strategies, myths, and the cognitive benefits of two languages.',
    why_we_picked: 'The definitive practical guide for bilingual families. Covers every scenario from one-parent-one-language to community language support.',
    is_free_online: false,
  },
];
